### PR TITLE
Retrieve training dataset in lecture 20 using gdown

### LINKED ISSUE #7: move storage and retrieval of cs-506-midterm-a1-b1
One of the files for the Recommender lecture is not included. Need to store somewhere else and fetch.

> From Mark
> 
> Just FYI if you want to obtain the file in the future you can:
>  
> pip install kaggle
> put the attached file in your ~/.kaggle
> kaggle competitions download -c cs-506-midterm-a1-b1
> 

[kaggle.json](https://github.com/user-attachments/files/16071492/kaggle.json)

### PR DESCRIPTION
**Pull request by sladenheim**
Implemented  the use of gdown to download training data (train.csv) in 20-Recommender-Systems. The download worked during the build, however there was another issue in this lecture that stopped the build.

Closes #7

### CODE REVIEW

**Comment by trgardos** [comment]
Is the other you mentioned above addressed too?

Also, can we merge #22 first, and then I will update the merge conflicts for this PR and then we can merge this one.

**Comment by sladenheim** [comment]
Yes. Merge 22 first. Then I'll rebase my branch on top of that one. I can then sort out the other issue in the build as well.

**Comment by trgardos** [comment]
Ok, I fixed the existing conflict and then added lecture 20 back in on the quarto profile config _quarto_web.yml.

Are we good to merge? Or is there another issue with the notebook?

**Review by trgardos — APPROVED** [review]

**Comment by sladenheim** [comment]
I am going to merge. The download of the file should be working. If the build fails I will take a look and fix it.

**Pull request merged**
